version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: AgroServis/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=AgroServis;User Id=sa;Password=myPassword1!;TrustServerCertificate=True

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "myPassword1!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P myPassword1! -Q 'SELECT 1' -C"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  sql_data: